### ISSUE TITLE
sendRawTranaction is throwing exception.

### ISSUE THREAD

**Issue by satran004** [satran004/aion-graphql#2]
org.satran.blockchain.graphql.exception.BlockChainAcessException: Function exception!
        at org.satran.blockchain.graphql.impl.aion.service.TxnServiceImpl.lambda$sendRawTransaction$15(TxnServiceImpl.java:486)
        at org.satran.blockchain.graphql.impl.aion.service.dao.AionBlockchainAccessor.call(AionBlockchainAccessor.java:34)
        at org.satran.blockchain.graphql.impl.aion.service.TxnServiceImpl.sendRawTransaction(TxnServiceImpl.java:481)
        at org.satran.blockchain.graphql.resolvers.TxnMutator.sendRawTransaction(TxnMutator.java:49)
        at org.satran

**Comment by satran004** [comment]
https://github.com/satran004/aion-graphql/commit/8a6fff1a530d0b87d1afd9381ed479a96471f052
